Repository ferriskey/ferriskey, pull requests merged in 2025-09, with the labels that each got.

#415 feat: add name and description on webhook
  api/src/application/http/webhook/handlers/create_webhook.rs
  api/src/application/http/webhook/handlers/update_webhook.rs
  api/src/application/http/webhook/validators.rs
  core/migrations/20250823153601_add_name_and_description_to_webhook.down.sql
  core/migrations/20250823153601_add_name_and_description_to_webhook.up.sql
  core/src/application/webhook/use_cases/create_webhook_use_case.rs
  core/src/application/webhook/use_cases/update_webhook_use_case.rs
  core/src/domain/webhook/ports.rs
  core/src/domain/webhook/services/webhook_service.rs
  core/src/entity/clients.rs
  core/src/entity/webhooks.rs
  core/src/infrastructure/client/mappers/client_mapper.rs
  core/src/infrastructure/client/repositories/client_postgres_repository.rs
  core/src/infrastructure/webhook/repository.rs
Labels: type:feature, scope:api, scope:core

#416 ci(docker): avoid running if no important files changed
  .dockerignore
  .github/workflows/docker.yaml
Labels: type:ci

#418 ci(release): refactor
  .github/release-drafter.yml
  .github/release.yaml
  .github/workflows/release-candidate.yaml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yaml
Labels: type:ci

#422 fix: update profiles and environment for registry services
  docker-compose.yaml
Labels: type:bug, scope:infra

#423 feat: implement delete role action
  api/src/application/http/role/handlers/delete_role.rs
  api/src/application/http/role/handlers/get_role.rs
  api/src/application/http/role/handlers/update_role.rs
  api/src/application/http/role/handlers/update_role_permissions.rs
  api/src/application/http/role/router.rs
  api/src/application/http/user/handlers/assign_role.rs
  api/src/application/http/user/handlers/get_user.rs
  api/src/application/http/user/handlers/get_user_roles.rs
  core/src/application/common/factories.rs
  core/src/application/role/mod.rs
  core/src/application/role/policies.rs
  core/src/application/role/use_cases.rs
  core/src/application/role/use_cases/delete_role_use_case.rs
  core/src/application/role/use_cases/get_roles_use_case.rs
  core/src/application/role/use_cases/update_role_permissions_use_case.rs
  core/src/application/role/use_cases/update_role_use_case.rs
  front/src/api/api.client.ts
  front/src/api/role.api.ts
  front/src/pages/client/feature/page-client-roles-feature.tsx
  front/src/pages/client/ui/page-client-roles.tsx
  front/src/pages/role/feature/page-roles-overview-feature.tsx
  front/src/pages/role/ui/page-roles-overview.tsx
Labels: type:feature

#441 feat: add comprehensive error types to core domain
  core/src/domain/common/entities/app_errors.rs
Labels: type:refactor, scope:core

#443 refactor: trident domain & policy enforcer
  core/src/application/common/permissions.rs
  core/src/application/trident/mod.rs
  core/src/domain/crypto/ports.rs
  core/src/domain/crypto/services.rs
  core/src/domain/trident/ports.rs
Labels: type:refactor

#444 refactor: add FerriskeyPolicy to FerriskeyService and implement
  core/src/application/common/mod.rs
  core/src/application/common/permissions.rs
Labels: type:refactor

#459 refactor: migrate realm service from use cases to service module
  core/src/application/client/use_cases/delete_redirect_uri_use_case.rs
  core/src/application/common/services.rs
  core/src/application/realm/mod.rs
  core/src/application/realm/service.rs
  core/src/application/realm/use_cases/create_realm_use_case.rs
  core/src/application/realm/use_cases/delete_realm_use_case.rs
  core/src/application/realm/use_cases/get_realm_use_case.rs
  core/src/application/realm/use_cases/get_user_realms_settings_use_case.rs
  core/src/application/realm/use_cases/get_user_realms_use_case.rs
  core/src/application/realm/use_cases/update_realm_settings_use_case.rs
  core/src/application/realm/use_cases/update_realm_use_case.rs
  core/src/domain/realm/mod.rs
  core/src/domain/realm/policies.rs
  core/src/domain/realm/ports.rs
  core/src/domain/realm/services.rs
  core/src/infrastructure/realm/repositories.rs
  core/src/infrastructure/realm/repositories/realm_postgres_repository.rs
Labels: type:refactor, scope:api, scope:core

#470 fix: remove version pinning for ca-certificates and libssl3
  Dockerfile
Labels: type:bug, type:ci

#474 refactor: enhance core
  api/src/application/http/client.rs
  api/src/application/http/client/errors.rs
  api/src/application/http/realm.rs
  api/src/application/http/realm/errors.rs
  api/src/application/http/role.rs
  api/src/application/http/role/errors.rs
  api/src/application/http/user/errors.rs
  api/tests/it/main.rs
  core/src/application/common/mod.rs
  core/src/application/realm/mod.rs
  core/src/application/realm/policies.rs
  core/src/domain/authentication/services.rs
  core/src/domain/authentication/services/auth_session_service.rs
  core/src/domain/client/entities.rs
  core/src/domain/client/entities/redirect_uri.rs
  core/src/domain/client/ports.rs
  core/src/domain/common/policies.rs
  core/src/domain/mediator/mod.rs
  core/src/domain/mod.rs
  core/src/domain/realm/entities.rs
  core/src/domain/realm/mod.rs
  core/src/domain/role/entities.rs
  core/src/domain/role/ports.rs
  core/src/domain/trident/entities.rs
  core/src/domain/trident/mod.rs
  core/src/domain/trident/ports.rs
  core/src/domain/trident/services.rs
  core/src/domain/user/entities.rs
  core/src/domain/user/ports.rs
  core/src/domain/user/services/user_role_service.rs
  core/src/infrastructure/client/repositories.rs
  core/src/infrastructure/client/repositories/client_postgres_repository.rs
  core/src/infrastructure/client/repositories/redirect_uri_postgres_repository.rs
  core/src/infrastructure/repositories.rs
  core/src/infrastructure/role/repositories.rs
  core/src/infrastructure/role/repositories/role_postgres_repository.rs
  core/src/infrastructure/user.rs
  core/src/infrastructure/user/repositories/user_role_repository.rs
  core/src/infrastructure/user/repository.rs
  core/src/infrastructure/webhook/repositories/webhook_notifier_repository.rs
Labels: type:refactor

#479 refactor: role module by splitting policies and services
  core/src/application/role/mod.rs
  core/src/application/role/policies.rs
  core/src/application/role/services.rs
Labels: type:refactor

#481 refactor: rework operator
  Cargo.lock
  core/src/application/common/mod.rs
  operator/Cargo.toml
  operator/crds/crd-ferriskeycluster.yaml
  operator/src/application/mod.rs
  operator/src/application/services.rs
  operator/src/application/services/cluster.rs
  operator/src/bin/crdgen.rs
  operator/src/controller/cluster.rs
  operator/src/controller/cluster/api.rs
  operator/src/controller/cluster/frontend.rs
  operator/src/controller/cluster/postgres.rs
  operator/src/crd.rs
  operator/src/crd/cluster.rs
  operator/src/domain/cluster.rs
  operator/src/domain/error.rs
  operator/src/domain/mod.rs
  operator/src/infrastructure/cluster/crds.rs
  operator/src/infrastructure/cluster/manifests/api.rs
  operator/src/infrastructure/cluster/manifests/api/deployment.rs
  operator/src/infrastructure/cluster/manifests/api/job.rs
  operator/src/infrastructure/cluster/manifests/api/secret.rs
  operator/src/infrastructure/cluster/manifests/api/service.rs
  operator/src/infrastructure/cluster/manifests/mod.rs
  operator/src/infrastructure/cluster/mod.rs
  operator/src/infrastructure/cluster/repositories.rs
  operator/src/infrastructure/cluster/repositories/k8s.rs
  operator/src/infrastructure/ferriskey_client.rs
  operator/src/infrastructure/mod.rs
  operator/src/lib.rs
  operator/src/main.rs
Labels: type:refactor
