Repository ferriskey/ferriskey, pull requests merged in 2025-08, with the labels that each got.

#291 feat: configure Docker setup with new Dockerfile and update CI context
  .dockerignore
  .github/workflows/release-candidate.yaml
  .github/workflows/release-dev.yml
  docker/Dockerfile
Labels: type:ci, priority-1

#293 feat: add health check endpoints and service implementation
  api/src/lib/application/http.rs
  api/src/lib/application/http/health/handlers/health_live.rs
  api/src/lib/application/http/health/handlers/health_ready.rs
  api/src/lib/application/http/health/handlers/mod.rs
  api/src/lib/application/http/health/mod.rs
  api/src/lib/application/http/server/http_server.rs
  core/src/application/common/factories.rs
  core/src/application/common/services.rs
  core/src/application/health/mod.rs
  core/src/application/health/use_cases.rs
  core/src/application/mod.rs
  core/src/domain/health/entities.rs
  core/src/domain/health/mod.rs
  core/src/domain/health/ports.rs
  core/src/domain/health/services.rs
  core/src/domain/mod.rs
  core/src/infrastructure/common/factories/service_factory.rs
  core/src/infrastructure/health/mod.rs
  core/src/infrastructure/health/repositories.rs
  core/src/infrastructure/mod.rs
  infrastructure/charts/ferriskey/templates/api/deployment.yaml
  infrastructure/charts/ferriskey/values.yaml
Labels: type:feature, scope:api, priority-1

#298 Safe handling of session cookie unwrapping
  api/src/lib/application/http/authentication/handlers/authentificate.rs
Labels: type:bug, scope:api

#300 Removed 2 un-necessary clones
  api/src/bin/main.rs
  core/src/application/common/factories.rs
Labels: type:refactor, scope:api

#307 fix: remove tagging as latest in release workflow for helm chart
  .github/workflows/release.yaml
Labels: type:ci

#310 fix: remove unnecessary Arc import and simplify iterator chaining
  api/src/lib/application/http/server/http_server.rs
  api/tests/it/postgres_context.rs
Labels: type:bug

#311 feat: enhance readme
  CONTRIBUTING.md
  README.md
Labels: type:doc

#324 fix: add missing entity directory copy in Dockerfile
  docker/Dockerfile
Labels: type:ci

#329 Improve workspace management
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  core/Cargo.toml
  operator/Cargo.toml
  operator/src/bin/crdgen.rs
Labels: type:refactor, scope:api, scope:core, scope:operator, type:build

#325 feat: typed openapi & type-safety react-query
  front/openapi.yaml
  front/package.json
  front/pnpm-lock.yaml
  front/src/api/api.client.ts
  front/src/api/api.tanstack.ts
  front/src/api/client.api.ts
  front/src/api/index.ts
  front/src/pages/client/columns/list-client.column.tsx
  front/src/pages/client/components/manage-redirect-uris.tsx
  front/src/pages/client/feature/page-client-credentials-feature.tsx
  front/src/pages/client/feature/page-client-settings-feature.tsx
  front/src/pages/client/feature/page-clients-overview-feature.tsx
  front/src/pages/client/layout/client-layout.tsx
  front/src/pages/client/ui/page-client-credentials.tsx
  front/src/pages/client/ui/page-client-settings.tsx
  front/src/pages/client/ui/page-clients-overview.tsx
  front/src/pages/role/ui/components/select-client-box.tsx
  front/src/pages/role/ui/page-create-role.tsx
Labels: type:refactor

#332 entity: remove
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/entity/auth_sessions.rs
  core/src/entity/clients.rs
  core/src/entity/credentials.rs
  core/src/entity/jwt_keys.rs
  core/src/entity/mod.rs
  core/src/entity/prelude.rs
  core/src/entity/realm_settings.rs
  core/src/entity/realms.rs
  core/src/entity/redirect_uris.rs
  core/src/entity/refresh_tokens.rs
  core/src/entity/roles.rs
  core/src/entity/user_required_actions.rs
  core/src/entity/user_role.rs
  core/src/entity/user_sessions.rs
  core/src/entity/users.rs
  core/src/infrastructure/client/mappers.rs
  core/src/infrastructure/realm/mappers.rs
  core/src/infrastructure/repositories/auth_session_repository.rs
  core/src/infrastructure/repositories/client_repository.rs
  core/src/infrastructure/repositories/credential_repository.rs
  core/src/infrastructure/repositories/keystore_repository.rs
  core/src/infrastructure/repositories/realm_repository.rs
  core/src/infrastructure/repositories/redirect_uri_repository.rs
  core/src/infrastructure/repositories/refresh_token_repository.rs
  core/src/infrastructure/repositories/role_repository.rs
  core/src/infrastructure/repositories/user_session_repository.rs
  core/src/infrastructure/user/links.rs
  core/src/infrastructure/user/mappers.rs
  core/src/infrastructure/user/repositories/user_required_action_repository.rs
  core/src/infrastructure/user/repositories/user_role_repository.rs
  core/src/infrastructure/user/repository.rs
  core/src/lib.rs
  entity/Cargo.toml
Labels: type:refactor, scope:core

#338 docker: rewrite image to optimize cache
  .dockerignore
  .github/workflows/docker.yaml
  Dockerfile
  api/Cargo.lock
  api/Dockerfile
  core/Cargo.lock
  docker/Dockerfile
  front/.dockerignore
  front/Dockerfile
  operator/.dockerignore
  operator/Cargo.lock
  operator/Dockerfile
Labels: type:refactor, type:build

#339 ci(docker): improve cache
  .github/workflows/docker.yaml
Labels: type:bug, type:ci

#340 ci(docker): move permissions at top level
  .github/workflows/docker.yaml
Labels: type:bug, type:ci

#346 pre-commit: add hadolint
  .dockerignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Dockerfile
Labels: type:ci, type:build

#347 refacto: remove typeshare
  .github/workflows/release-dev.yml
  Cargo.lock
  api/Cargo.toml
  api/build.rs
  api/src/application/http/authentication/handlers/auth.rs
  api/src/application/http/authentication/handlers/authentificate.rs
  api/src/application/http/authentication/handlers/get_certs.rs
  api/src/application/http/authentication/handlers/openid_configuration.rs
  api/src/application/http/authentication/validators.rs
  api/src/application/http/client/handlers/delete_client.rs
  api/src/application/http/client/handlers/get_client.rs
  api/src/application/http/client/handlers/get_clients.rs
  api/src/application/http/realm/handlers/get_user_realms.rs
  api/src/application/http/role/handlers/get_role.rs
  api/src/application/http/role/handlers/get_roles.rs
  api/src/application/http/role/handlers/update_role.rs
  api/src/application/http/role/handlers/update_role_permissions.rs
  api/src/application/http/role/validators.rs
  api/src/application/http/server/config.rs
  api/src/application/http/trident/handlers/challenge_otp.rs
  api/src/application/http/trident/handlers/setup_otp.rs
  api/src/application/http/trident/handlers/verify_otp.rs
  api/src/application/http/trident/validators.rs
  api/src/application/http/user/handlers/bulk_delete_user.rs
  api/src/application/http/user/handlers/create_user.rs
  api/src/application/http/user/handlers/delete_credential.rs
  api/src/application/http/user/handlers/delete_user.rs
  api/src/application/http/user/handlers/get_credentials.rs
  api/src/application/http/user/handlers/get_user.rs
  api/src/application/http/user/handlers/get_user_roles.rs
  api/src/application/http/user/handlers/get_users.rs
  api/src/application/http/user/handlers/update_user.rs
  api/src/env.rs
  core/Cargo.toml
  core/build.rs
  core/src/application/authentication/use_cases/authenticate_use_case.rs
  core/src/domain/authentication/entities.rs
  core/src/domain/client/entities.rs
  core/src/domain/client/entities/redirect_uri.rs
  core/src/domain/credential/entities.rs
  core/src/domain/jwt/entities.rs
  core/src/domain/realm/entities.rs
  core/src/domain/role/entities.rs
  core/src/domain/role/entities/permission.rs
  core/src/domain/user/entities.rs
Labels: type:refactor

#350 fix: sidebar context imports and usage
  front/src/components/ui/sidebar.tsx
  front/src/pages/client/feature/page-create-client-feature.tsx
Labels: type:bug

#357 feat: add http webhook endpoints
  api/src/application/http.rs
  api/src/application/http/server/api_entities/api_error.rs
  api/src/application/http/server/http_server.rs
  api/src/application/http/server/openapi.rs
  api/src/application/http/webhook.rs
  api/src/application/http/webhook/errors.rs
  api/src/application/http/webhook/handlers.rs
  api/src/application/http/webhook/handlers/create_webhook.rs
  api/src/application/http/webhook/handlers/delete_webhook.rs
  api/src/application/http/webhook/handlers/fetch_webhook.rs
  api/src/application/http/webhook/handlers/get_webhook.rs
  api/src/application/http/webhook/handlers/update_webhook.rs
  api/src/application/http/webhook/router.rs
  api/src/application/http/webhook/validators.rs
  core/src/application/common/factories.rs
  core/src/application/mod.rs
  core/src/application/webhook/mod.rs
  core/src/application/webhook/policies.rs
  core/src/application/webhook/use_cases.rs
  core/src/application/webhook/use_cases/create_webhook_use_case.rs
  core/src/application/webhook/use_cases/delete_webhook_use_case.rs
  core/src/application/webhook/use_cases/fetch_realm_webhooks_use_case.rs
  core/src/application/webhook/use_cases/get_webhook_use_case.rs
  core/src/application/webhook/use_cases/update_webhook_use_case.rs
  core/src/domain/role/entities/permission.rs
  core/src/domain/webhook/entities.rs
Labels: type:feature, scope:api

#354 chore: update axum-prometheus to 0.9.0
  Cargo.lock
  api/Cargo.toml
Labels: type:feature

#361 feat(realms): adding frontend for realm settings
  CONTRIBUTING.md
  front/src/App.css
  front/src/App.tsx
  front/src/api/api.client.ts
  front/src/api/core.interface.ts
  front/src/api/core.mapper.ts
  front/src/components/nav-configuration.tsx
  front/src/components/ui/select.tsx
  front/src/components/ui/tabs.tsx
  front/src/components/work-in-progress.tsx
  front/src/hooks/use-feature.ts
  front/src/lib/features.ts
  front/src/pages/realm/feature/page-realm-settings-general-feature.tsx
  front/src/pages/realm/feature/page-realm-settings-login-feature.tsx
  front/src/pages/realm/feature/page-realm-settings-security-feature.tsx
  front/src/pages/realm/layouts/realm-settings-layout.tsx
  front/src/pages/realm/page-realm.tsx
  front/src/pages/realm/ui/page-realm-settings-general.tsx
  front/src/pages/realm/ui/page-realm-settings.tsx
  front/src/pages/realm/validators.ts
  front/src/pages/role/feature/page-role-users-feature.tsx
  front/src/pages/user/ui/page-user-overview.tsx
  front/src/routes/router.ts
  front/src/routes/sub-router/client.router.ts
  front/src/routes/sub-router/realm.router.ts
Labels: type:feature

#362 docker: define uid/gid for ferriskey user
  Dockerfile
Labels: type:build

#367 docker: move migrations into /usr/local/src
  Dockerfile
Labels: type:build

#392 fix: translated french words
  front/src/components/ui/data-table.tsx
  front/src/pages/client/columns/list-client.column.tsx
Labels: type:bug

#396 ci(docker): push when merge on main
  .github/workflows/docker.yaml
Labels: type:ci

#402 feat: implement client webhook notifier
  core/src/application/client/use_cases.rs
  core/src/application/client/use_cases/create_client_use_case.rs
  core/src/application/client/use_cases/create_redirect_uri_use_case.rs
  core/src/application/client/use_cases/create_role_use_case.rs
  core/src/application/client/use_cases/delete_client_use_case.rs
  core/src/application/client/use_cases/update_client_use_case.rs
  core/src/application/client/use_cases/update_redirect_uri_use_case.rs
  core/src/domain/webhook/entities/webhook_trigger.rs
Labels: type:feature, scope:core

#408 feat: move to one thread and add dynamic payload under the webhook
  core/src/domain/webhook/entities/webhook_payload.rs
  core/src/domain/webhook/ports.rs
  core/src/domain/webhook/services/webhook_notifier_service.rs
Labels: type:feature, scope:core

#409 feat: create webhook error for each use case domain
  api/src/application/http/client/errors.rs
  api/src/application/http/realm/errors.rs
  api/src/application/http/role/errors.rs
  api/src/application/http/user/errors.rs
  core/src/application/client/use_cases.rs
  core/src/application/client/use_cases/create_client_use_case.rs
  core/src/application/client/use_cases/create_redirect_uri_use_case.rs
  core/src/application/client/use_cases/create_role_use_case.rs
  core/src/application/client/use_cases/delete_client_use_case.rs
  core/src/application/client/use_cases/delete_redirect_uri_use_case.rs
  core/src/application/client/use_cases/update_client_use_case.rs
  core/src/application/client/use_cases/update_redirect_uri_use_case.rs
  core/src/application/realm/use_cases/create_realm_use_case.rs
  core/src/application/realm/use_cases/delete_realm_use_case.rs
  core/src/application/realm/use_cases/update_realm_settings_use_case.rs
  core/src/application/realm/use_cases/update_realm_use_case.rs
  core/src/application/role/use_cases/update_role_permissions_use_case.rs
  core/src/application/role/use_cases/update_role_use_case.rs
  core/src/application/user/use_cases/assign_role_use_case.rs
  core/src/application/user/use_cases/bulk_delete_user.rs
  core/src/application/user/use_cases/create_user_use_case.rs
  core/src/application/user/use_cases/delete_credential_use_case.rs
  core/src/application/user/use_cases/delete_user_use_case.rs
  core/src/application/user/use_cases/reset_password_use_case.rs
  core/src/application/user/use_cases/unassign_role_use_case.rs
  core/src/application/user/use_cases/update_user_use_case.rs
  core/src/domain/client/entities.rs
  core/src/domain/realm/entities.rs
  core/src/domain/role/entities.rs
  core/src/domain/user/entities.rs
  core/src/domain/webhook/entities/webhook_trigger.rs
Labels: type:feature, scope:core

#411 feat: change string to webhook_trigger in signatures
  core/src/domain/webhook/entities/webhook_subscriber.rs
  core/src/domain/webhook/entities/webhook_trigger.rs
  core/src/infrastructure/repositories.rs
  core/src/infrastructure/repositories/webhook_repository.rs
  core/src/infrastructure/webhook/mappers.rs
  core/src/infrastructure/webhook/repository.rs
Labels: type:feature, scope:core
