Repository ferriskey/ferriskey, pull requests merged in 2025-03, with the labels that each got.

#6 feat: add Docker Compose configuration for PostgreSQL and Keycloak
  docker-compose.yml
Labels: type:feature

#7 feat: enhance realm management with create_realm_master functionality
  .gitignore
  api/rustfmt.toml
  api/src/bin/main.rs
  api/src/lib/domain/realm/entities/model.rs
  api/src/lib/domain/realm/ports.rs
  api/src/lib/domain/realm/service.rs
  docker-compose.yml
Labels: type:feature

#11 feat: enhance OpenAPI documentation for realm management
  api/src/lib/application/http.rs
  api/src/lib/application/http/handlers/realm.rs
  api/src/lib/application/http/handlers/realm/create_realm.rs
  api/src/lib/application/http/openapi.rs
Labels: type:refactor

#16 feat: implements client schema and endpoints
  api/Cargo.lock
  api/Cargo.toml
  api/migrations/20250320192139_add_clients.up.sql
  api/src/lib/application/http.rs
  api/src/lib/application/http/client/errors.rs
  api/src/lib/application/http/client/handlers/create_client.rs
  api/src/lib/application/http/client/handlers/mod.rs
  api/src/lib/application/http/client/mod.rs
  api/src/lib/application/http/client/router.rs
  api/src/lib/application/http/client/validators.rs
  api/src/lib/application/http/server/http_server.rs
  api/src/lib/application/http/server/openapi.rs
  api/src/lib/domain/client/entities/model.rs
  api/src/lib/domain/client/ports.rs
  api/src/lib/domain/client/service.rs
  api/src/lib/infrastructure/repositories/client_repository.rs
Labels: type:feature

#19 feat: add release drafter configuration and workflow
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: type:ci

#17 feat/implement realms
  api/migrations/20250322185202_realm_settings.down.sql
  api/migrations/20250322185202_realm_settings.up.sql
  api/src/lib/application/http/realm/handlers.rs
  api/src/lib/application/http/realm/handlers/create_realm.rs
  api/src/lib/application/http/realm/handlers/delete_realm.rs
  api/src/lib/application/http/realm/handlers/fetch_realm.rs
  api/src/lib/application/http/realm/handlers/get_realm.rs
  api/src/lib/application/http/realm/handlers/update_realm.rs
  api/src/lib/application/http/realm/handlers/update_realm_setting.rs
  api/src/lib/application/http/realm/router.rs
  api/src/lib/application/http/realm/validators.rs
  api/src/lib/domain.rs
  api/src/lib/domain/realm/entities.rs
  api/src/lib/domain/realm/entities/realm.rs
  api/src/lib/domain/realm/entities/realm_setting.rs
  api/src/lib/domain/realm/ports.rs
  api/src/lib/domain/realm/service.rs
  api/src/lib/domain/utils.rs
  api/src/lib/infrastructure/repositories/realm_repository.rs
Labels: type:feature

#21 feat: implement response enum and applied it
  api/src/lib/application/http/client/handlers/create_client.rs
  api/src/lib/application/http/realm/handlers/create_realm.rs
  api/src/lib/application/http/realm/handlers/delete_realm.rs
  api/src/lib/application/http/realm/handlers/fetch_realm.rs
  api/src/lib/application/http/realm/handlers/get_realm.rs
  api/src/lib/application/http/realm/handlers/update_realm.rs
  api/src/lib/application/http/realm/handlers/update_realm_setting.rs
  api/src/lib/application/http/server/handlers.rs
Labels: type:feature, scope:api

#22 feat: manage users
  api/Cargo.lock
  api/Cargo.toml
  api/migrations/20250323235038_add_users.down.sql
  api/migrations/20250323235038_add_users.up.sql
  api/migrations/20250323235041_add_credentials.down.sql
  api/migrations/20250323235041_add_credentials.up.sql
  api/src/bin/main.rs
  api/src/lib/application/http.rs
  api/src/lib/application/http/server/app_state.rs
  api/src/lib/application/http/server/http_server.rs
  api/src/lib/application/http/server/openapi.rs
  api/src/lib/application/http/user/errors.rs
  api/src/lib/application/http/user/handlers/mod.rs
  api/src/lib/application/http/user/handlers/reset_password.rs
  api/src/lib/application/http/user/mod.rs
  api/src/lib/application/http/user/router.rs
  api/src/lib/application/http/user/validators.rs
  api/src/lib/domain.rs
  api/src/lib/domain/credential/entities/error.rs
  api/src/lib/domain/credential/entities/mod.rs
  api/src/lib/domain/credential/entities/model.rs
  api/src/lib/domain/credential/mod.rs
  api/src/lib/domain/credential/ports.rs
  api/src/lib/domain/credential/service.rs
  api/src/lib/domain/crypto/mod.rs
  api/src/lib/domain/crypto/ports.rs
  api/src/lib/domain/user/entities/error.rs
  api/src/lib/domain/user/entities/mod.rs
  api/src/lib/domain/user/entities/model.rs
  api/src/lib/domain/user/mod.rs
  api/src/lib/domain/user/ports.rs
  api/src/lib/infrastructure/repositories.rs
  api/src/lib/infrastructure/repositories/argon2_hasher.rs
  api/src/lib/infrastructure/repositories/credential_repository.rs
  api/src/lib/infrastructure/repositories/realm_repository.rs
Labels: type:feature
